#!/bin/bash
###Fedora & OpenSUSE Sway Build + Redflower rice

#finding OS
. /etc/os-release
if [$NAME = "Fedora"*]; then
   dnf=ins
if [$NAME = "OpenSUSE"*]; then
   zypper=ins
else
  echo "can't find distro name"
fi

echo Initial stuff
sudo $ins update -y && sudo $ins system-upgrade -y

#Initial stuff
gnome-shell-extension-tool -e user-theme
gnome-shell-extension-tool -e user-theme@gnome-shell-extensions.gcampax.github.com

#Installing
echo Installing wlroots,sway,swaylock,swayidle,grim and waybar from rpm
  sudo rpm --import https://build.opensuse.org/projects/home:GeoDerp:redflower/public_key
  sudo $ins config-manager --add-repo https://download.opensuse.org/repositories/home:GeoDerp:redflower/Fedora_29/home:GeoDerp:redflower.repo
  sudo $ins install wlroots sway swaylock swayidle grim waybar wlstream -y
echo Installing Albert Launcher
  sudo rpm --import https://build.opensuse.org/projects/home:manuelschneid3r/public_key
  sudo $ins config-manager --add-repo https://download.opensuse.org/repositories/home:manuelschneid3r/Fedora_29/home:manuelschneid3r.repo
  sudo $ins install albert -y
echo "Installing [font awesome] for WayBar"
  cd ~/
  git clone https://github.com/FortAwesome/Font-Awesome.git
  cd Font-Awesome/webfonts/
  mkdir ~/.fonts
  mv * ~/.fonts/
  mv ~/Font-Awesome/otfs/* ~/.fonts/
  sudo wget "https://github.com/ox-it/hidden-museum/raw/master/fonts/Century%20Gothic.ttf" ~/.fonts/
  gsettings set org.gnome.desktop.interface monospace-font-name "Monospace Regular 11"
  gsettings set org.gnome.desktop.interface document-font-name 'Century Gothic Regular 10'
  gsettings set org.gnome.desktop.interface font-name 'Century Gothic Regular 11'

echo "installed nessesery tools, now installing configs for my rice"
echo "quite now if you want to do all the config yourself (ctl + C)"
sleep 10

echo "Installing terminal of choice  (unnessesery)"
  sudo $ins copr enable oleastre/kitty-terminal -y
  sudo $ins install kitty -y
##putting all configs and images into its right replacement
  ###(this is for ricing and you do not need it if you dont want yours to look like mine)
#wallpaper images
echo "wallpaper Images (there are two one Images, one christian, and one blank, on line 23 ish on ~/.config/sway/config there is a line with [output *bg ~/Pictures/Wallpapers/Wallpaper.jpg stretch] change Wallpaper.jpg or Blank.jpg depending on what you prefer more)"
sleep 10
  cd ~/SwayWM_Build/Images
  mkdir ~/Pictures/Wallpapers/
  mv * ~/Pictures/Wallpapers/
  sudo cp ~/Pictures/Wallpapers/Blank.jpg /usr/share/backgrounds/Blank.jpg
#GTK3 for GNOME
  cd ~/SwayWM_Build/dooooots/GTK3/theme/vimix-gtk-themes-master
  mkdir -p ~/.themes/
  chmod +x Install
  chmod +x parse-sass.sh
  ./Install -n VimixRedFlower -t ruby -o -f
  cd ~/SwayWM_Build/dooooots/GTK3/theme/VimixRedFlower
  mv * ~/.themes/VimixRedFlower-dark-ruby
  gsettings set org.gnome.desktop.interface gtk-theme VimixRedFlower-dark-ruby
#icon
  cd ~/SwayWM_Build/dooooots/GTK3/Icon/vimix-icon-theme-master
  mkdir ~/.icons
  cp -r RedFlower-Paper-Vimix ~/.icons/
  cp -r Vimix ~/.icons/
  cp -r Paper-Vimix ~/.icons/
echo "Applying Dark theme, you can use gnome-tweak letter to apply light theme"
  gsettings set org.gnome.desktop.interface icon-theme RedFlower-Paper-Vimix
  gtk-update-icon-cache RedFlower-Paper-Vimix
#cursor (x11 not wayland, might find a wayland verient down the line)
  cd ~/
  sudo $ins install inkscape xorg-x11-apps -y
  git clone https://github.com/keeferrourke/capitaine-cursors.git
  cd capitaine-cursors
  chmod +x build.sh
  ./build.sh
  gsettings set org.gnome.desktop.interface cursor-theme 'la capitaine'
#GDM (Login screen)
  #cd ~/SwayWM_Build/dooooots/GTK3/GDM
  #comming soon (.....maby)
#Grub theme (not tested and unnessesery)
  ##cd ~/
  ##github https://github.com/gustawho/grub2-theme-breeze.git
  ##cd grub2-theme-breeze
  ##sudo ./install.sh"
#irssi (for irc)
  #cd ~/SwayWM_Build/dooooots/irssi
  #$ins install irssi -y
  #mkdir ~/.irssi
  #mv * ~/.irssi/
  #config comming soon (maby)
#kitty (terminal)
  cd ~/SwayWM_Build/dooooots/kitty
  mkdir -p ~/.config/kitty
  mv * ~/.config/kitty/
#Albert config (my chosen aplication launcher (Aplication and theme install later))
  cd  ~/SwayWM_Build/dooooots/Albert
  mkdir ~/.config/albert
  mv * ~/.config/albert/
#sway (the wm)
  cd ~/SwayWM_Build/dooooots/sway
  mkdir ~/.config/sway
  mv * ~/.config/sway/
#WayBar (the bar replacment for swaybar, wayland version of polybar for i3wm)
  cd ~/SwayWM_Build/dooooots/waybar
  mkdir ~/.config/waybar
  mv * ~/.config/waybar/
#Albert (Aplication Launcher)
  #Installing albert RedFlower theme
  cd ~/SwayWM_Build/dooooots/AlbertTheme
  mkdir -p /home/geo/.local/share/albert/org.albert.frontend.widgetboxmodel/themes
  sudo mv * "/home/geo/.local/share/albert/org.albert.frontend.widgetboxmodel/themes/"

echo "Finnished rice :D"
echo "Installing Regular used applications (completely unnecessary)"
echo "quite now if you want to do all my applications use (ctl + C)"
sleep 15

sudo $ins install flatpak -y
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#Atom (Prefered IDE)
  cd ~/
  sudo rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey
  sudo sh -c 'echo -e "[Atom]\nname=Atom Editor\nbaseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey" > /etc/yum.repos.d/atom.repo'
  sudo $ins install atom-beta -y
  mkdir ~/.atom
  cd ~/SwayWM_Build/dooooots/.atom
  sudo mv * ~/.atom/
#Spodify (Music Player)
  sudo flatpak install flathub com.spotify.Client -y
#keepassxc (Password Manager)
  sudo $ins install keepassxc -y
#LibreOffice (office)
  sudo $ins groupinstall LibreOffice -y
#security applications
  #sudo $ins groupinstall security-lab -y
  #intsall day-n-day apps (unnessesery)
##installing nano (Prefered Terminal Text Editor)
  sudo $ins install nano -y
##Google chrome (Prefered Web Browser, only working for Fedora)
  sudo $ins install fedora-workstation-repositories -y
  sudo $ins config-manager --set-enabled google-chrome
  sudo $ins install google-chrome-beta -y
##franz (Multi Messaging Aplication)
  cd ~/
  sudo wget https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.22/franz-5.0.0-beta.22-x86_64.AppImage
  sudo chmod a+x franz-5.0.0-beta.22-x86_64.AppImage
  ./franz-5.0.0-beta.22-x86_64.AppImage
  rm franz-5.0.0-beta.22-x86_64.AppImage

echo "finnished, Have fun, Hopfully everything works :)"
echo "Now restarting"
  sleep 35
  sudo init 6
