#!/bin/bash
###Fedora & OpenSUSE Sway Build + Redflower rice

#finding OS
. /etc/os-release
if [[ $NAME = Fedora* ]]
then ins=dnf
elif  [[ $NAME = openSUSE* ]]
then ins=zypper
elif [[ ! -z "$OSTREE_VERSION" ]] #For SilverBlue (SilverBlue may not work on riceing stage, haven't tested)
then ins=rpm-ostree
else echo "can't find distro name, defaulting to Fedora" && ins=dnf
fi

#configuring Update + OS veribles  
if [[ $NAME = Fedora* ]]
then upd="sudo dnf update -y" && os="$NAME"_"$VERSION_ID"
elif [[ ! -z "$OSTREE_VERSION" ]] #For Silverteam 
then upd='rpm-ostree upgrade -y' && os="$NAME"_"$VERSION_ID"
elif  [[ $NAME = "openSUSE Leap" ]]
then upd="sudo zypper up -y" && os="$NAME"_"$VERSION_ID"
elif  [[ $NAME = "openSUSE Tumbleweed" ]]
then upd="sudo zypper dup -y" && os=$NAME
else echo "can't find distro name"
fi

echo ""
echo ""
echo -e "\e[1mHello, and welcome to the Sway Wm Intsall script\e[0m"
echo -e "\e[93m------------------------------------------------------------------------------------------------------------\e[39m"
echo -e "Type: \e[4m1\e[0m: If you only want to only install the \e[94mBase packages\e[39m (no rice)"
echo -e "Type: \e[4m2\e[0m, If you want \e[94mBase Packages\e[39m + \e[91mRice\e[39m"
echo -e "Type: \e[4m3\e[0m, If you want \e[94mBase Packages\e[39m + \e[91mRice\e[39m + additional \e[92mgeneric aplications\e[39m"
echo -e "Type: \e[4m4\e[0m, If you want only the \e[91mRice\e[39m (Would need base packages installed in some way)"
echo -e "\e[93m-------------------------------------------------------------------------------------------------------------\e[39m"
read -n1 -p "Type [1,2,3 or 4]" Choice
echo -e "\e[1mRunning Choice\e[0m: \e[5m$Choice\e[0;39m"

if [[ $Choice = 1 ]] || [[ $Choice = 2 ]] || [[ $Choice = 3 ]]
then {
echo ""
echo -e "\e[93m-------------------------------------------------------------------------------------------------------------\e[39m"
echo -e "\e[1mBase packages:\e[0m \e[94m(Stage 1)\e[39m"
echo ""
echo "Initial stuff"
sudo $ins update -y

echo "Updating"
$upd

#Initial stuff
gnome-shell-extension-tool -e user-theme
gnome-shell-extension-tool -e user-theme@gnome-shell-extensions.gcampax.github.com

#Installing
echo "Installing ffmpeg (For sway)"
if [[ $NAME = Fedora* ]] || [[ ! -z "$OSTREE_VERSION" ]]
  then 
  sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y 
  sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
  dnf clean all
  dnf repolist
  sudo dnf install ffmpeg-devel -y 
fi
echo "Installing wlroots,sway,swaylock,swayidle,albert,grim and waybar from rpm"
  sudo rpm --import https://build.opensuse.org/projects/home:GeoDerp:redflower/public_key
  sudo $ins config-manager --add-repo "https://download.opensuse.org/repositories/home:/GeoDerp:/redflower/"$os"/home:GeoDerp:redflower.repo"
  $ins clean all
  $ins repolist
  sudo $ins install wlroots-devel celt fmt-devel sway swaylock swayidle albert grim waybar -y
 #doing commands again (sometimes is buggy) , if still no intsall after finish run script manually (copy and past into terminal), from start up to the end of stage 1
  sudo $ins config-manager --add-repo "https://download.opensuse.org/repositories/home:/GeoDerp:/redflower/"$os"/home:GeoDerp:redflower.repo"
  sudo $ins install wlroots-devel celt fmt-devel sway swaylock swayidle albert grim waybar -y
  #making sure swaylock has login authentication
  sudo bash -c ' echo "auth include login" > /etc/pam.d/swaylock'
  # since albert only works in xwayland for the time being we have to tell it to run in xwayland and not wayland 
  sudo bash -c ' echo export QT_QPA_PLATFORM="xcb" >> /etc/profile.d/albert.sh'
  source /etc/profile.d/albert.sh
echo "Installing [font awesome] for WayBar"
  cd ~/
  git clone https://github.com/FortAwesome/Font-Awesome.git
  mkdir ~/.fonts
  mv ~/Font-Awesome/webfonts/*.ttf ~/.fonts/
  sudo rm -r ~/Font-Awesome # clean up 
  sudo wget "https://github.com/ox-it/hidden-museum/raw/master/fonts/Century%20Gothic.ttf" ~/.fonts/
  gsettings set org.gnome.desktop.interface monospace-font-name "Monospace Regular 11"
  gsettings set org.gnome.desktop.interface document-font-name 'Century Gothic Regular 10'
  gsettings set org.gnome.desktop.interface font-name 'Century Gothic Regular 11'
#wf-recorder (Records and streams for wayland)
#  installing ffmpeg for encoding/decoding 
#  sudo $ins install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
#  sudo $ins install ffmpeg ffmpeg-devel -y
#  cd ~/
# git clone https://github.com/ammen99/wf-recorder && cd wf-recorder
#  meson build --prefix=/usr --buildtype=release
#  ninja -C build
}
fi

if [[ $Choice = 2 ]] || [[ $Choice = 4 ]] || [[ $Choice = 3 ]]
then {
echo ""
echo -e "\e[93m-------------------------------------------------------------------------------------------------------------\e[39m"
echo -e "\e[1mRicing:\e[0m \e[91m(Stage 2)\e[39m"
echo ""
echo "Installing kitty (terminal)"
  sudo $ins copr enable oleastre/kitty-terminal -y
  sudo $ins install kitty -y
##putting all configs and images into its right replacement
  ###(this is for ricing and you do not need it if you dont want yours to look like mine)
#wallpaper images
echo ""
echo ""
echo -e "\e[1mNote: with the Sway wallpaper Images, there are two images that can be used as wallpapers for Sway.\e[0m"
echo -e "\e[38;5;166m--------------------------------------------------------------------------------------------------------------------\e[39m"
echo -e "\e[96mOne christian\e[39m, and one \e[95mblank\e[39m."
echo -e "On line 23 on \e[4m~/.config/sway/config\e[0m there is a line with \e[4moutput *bg ~/Pictures/Wallpapers/Wallpaper.jpg stretch\e[0m change \e[96mWallpaper.jpg\e[39m or \e[95mBlank.jpg\e[39m depending on what you prefer more)"
echo -e "Wallpaper.jpg being the \e[96mChristian\e[39m one and \e[95mBlank.jpg\e[39m being, well, blank."
echo -e "\e[38;5;166m--------------------------------------------------------------------------------------------------------------------\e[39m"
echo -e "Feel free to go to the \e[4m~/Pictures/Wallpapers\e[0m dir to see the images for yourself."
echo ""
sleep 15
echo "Installing Albert Launcher"
  sudo $ins install albert -y
echo "Implementing Rice for: GTK3, Sway, Gnome Icons, x-cursor, kitty, Albert, Waybar"
  cd ~/SwayWM_Build/Images
  mkdir ~/Pictures/Wallpapers/
  mv * ~/Pictures/Wallpapers/
  sudo cp ~/Pictures/Wallpapers/Blank.jpg /usr/share/backgrounds/Blank.jpg
#GTK3 for GNOME
  cd ~/SwayWM_Build/dooooots/GTK3/theme/vimix-gtk-themes-master
  mkdir -p ~/.themes/
  chmod +x Install
  chmod +x parse-sass.sh
  ./Install -n VimixRedFlower -t ruby -o -f
  cd ~/SwayWM_Build/dooooots/GTK3/theme/VimixRedFlower
  mv * ~/.themes/VimixRedFlower-dark-ruby
  gsettings set org.gnome.desktop.interface gtk-theme VimixRedFlower-dark-ruby
#icon
  cd ~/SwayWM_Build/dooooots/GTK3/Icon/vimix-icon-theme-master
  mkdir ~/.icons
  cp -r RedFlower-Paper-Vimix ~/.icons/
  cp -r Vimix ~/.icons/
  cp -r Paper-Vimix ~/.icons/
echo "Applying Dark theme, you can use gnome-tweak letter to apply light theme"
  gsettings set org.gnome.desktop.interface icon-theme RedFlower-Paper-Vimix
  gtk-update-icon-cache RedFlower-Paper-Vimix
#cursor (x11 not wayland, might find a wayland verient down the line)
  cd ~/
  sudo $ins install inkscape xorg-x11-apps -y
  git clone https://github.com/keeferrourke/capitaine-cursors.git
  cd capitaine-cursors
  chmod +x build.sh
  ./build.sh
  gsettings set org.gnome.desktop.interface cursor-theme 'la capitaine'
#GDM (Login screen)
  #cd ~/SwayWM_Build/dooooots/GTK3/GDM
  #comming soon (.....maby)
#Grub theme (not tested and unnessesery)
  ##cd ~/
  ##github https://github.com/gustawho/grub2-theme-breeze.git
  ##cd grub2-theme-breeze
  ##sudo ./install.sh"
#irssi (for irc)
  #cd ~/SwayWM_Build/dooooots/irssi
  #$ins install irssi -y
  #mkdir ~/.irssi
  #mv * ~/.irssi/
  #config comming soon (maby)
#kitty (terminal)
  cd ~/SwayWM_Build/dooooots/kitty
  mkdir -p ~/.config/kitty
  mv * ~/.config/kitty/
#Albert config (my chosen aplication launcher (Aplication and theme install later))
  cd  ~/SwayWM_Build/dooooots/Albert
  mkdir ~/.config/albert
  mv * ~/.config/albert/
#sway (the wm)
  echo "installing packages for special keys"
  sudo $ins install brightnessctl pulseaudio -y
  cd ~/SwayWM_Build/dooooots/sway
  mkdir ~/.config/sway
  mv * ~/.config/sway/
#WayBar (the bar replacment for swaybar, wayland version of polybar for i3wm)
  cd ~/SwayWM_Build/dooooots/waybar
  mkdir ~/.config/waybar
  mv * ~/.config/waybar/
#Albert (Aplication Launcher)
  #Installing albert RedFlower theme
  cd ~/SwayWM_Build/dooooots/AlbertTheme
  mkdir -p /home/geo/.local/share/albert/org.albert.frontend.widgetboxmodel/themes
  sudo mv * "/home/geo/.local/share/albert/org.albert.frontend.widgetboxmodel/themes/"
echo "Finnished rice :D"
}
else exit
fi

if [[ $Choice = 3 ]]
then {
echo ""
echo -e "\e[93m-------------------------------------------------------------------------------------------------------------\e[39m"
echo -e "\e[1mInstalling app's:\e[0m \e[92m(Stage 3)\e[39m"
echo ""
echo "Apps: Atom, Spodify, Keepassxc, LibreOffice, nano, Google Chrome, Franz"
#Flatpak's
  sudo $ins install flatpak -y
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#Atom (Prefered IDE)
  cd ~/
  sudo rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey
  sudo sh -c 'echo -e "[Atom]\nname=Atom Editor\nbaseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey" > /etc/yum.repos.d/atom.repo'
  sudo $ins install atom-beta -y
  mkdir ~/.atom
  cd ~/SwayWM_Build/dooooots/.atom
  sudo mv * ~/.atom/
#Spodify (Music Player)
  sudo flatpak install flathub com.spotify.Client -y
#keepassxc (Password Manager)
  sudo $ins install keepassxc -y
#LibreOffice (office)
  sudo $ins groupinstall LibreOffice -y
#security applications
  #sudo $ins groupinstall security-lab -y
  #intsall day-n-day apps (unnessesery)
##installing nano (Prefered Terminal Text Editor)
  sudo $ins install nano -y
##Google chrome (Prefered Web Browser, only working for Fedora)
  sudo $ins install fedora-workstation-repositories -y
  sudo $ins config-manager --set-enabled google-chrome
  sudo $ins install google-chrome-beta -y
##franz (Multi Messaging Aplication)
  flatpak install flathub com.meetfranz.Franz -y 

echo "Updating"
$upd

echo "finished, Have fun, Hopefully everything works :D (let me know if it doesn't)"
echo "Now restarting"
  sleep 35
  sudo init 6
}
else exit
fi
